<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bokunorecipe"
 *
 * Auto generated by Extension Builder 2021-11-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BokuNoRecipe',
    'description' => 'This extension is for storing recipes in Typo3',
    'category' => 'plugin',
    'author' => 'Markus Ketterer',
    'author_email' => 'ketterer.markus@gmx.at',
    'state' => 'alpha',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
